

name: build cpp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build_cpp:
    runs-on: windows-latest

    steps:

      - name: ls
        run: ls
      - uses: actions/checkout@v3
      - name: env report
        run: |
          ls 
          printenv
      - name: build
        run: |
          cl /EHsc main.cpp
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: cpp_app
          path: main.exe
          retention-days: 5 
